### ISSUE TITLE
Custom UI/UX > UI Input Tables

### ISSUE THREAD

**Issue by margaretkennedy** [deephaven/deephaven-docs-community#112]
Reviewer = @arman-ddl 

Must include: https://deephaven.io/core/docs/how-to-guides/user-interface/add-clickable-links/

**Comment by elijahpetty** [comment]
OUTLINE: https://docs.google.com/document/d/1kz_2qQAV0lMQETyvGbBmRVh1UaKRnVo3zN7sR_gzqlc/edit
