### ISSUE TITLE
System set-up & admin: Authentication

### ISSUE THREAD

**Issue by margaretkennedy** [deephaven/deephaven-docs-community#123]
One page each for: 
- [ ] Anonymous
- [ ] Keycloak
- [ ] mTLS
- [ ] Pre-shared key
- [ ] Username/password

New Keycloak guide should include a section on adding new users to the Keycloak realm

**Comment by elijahpetty** [comment]
OUTLINES: https://docs.google.com/document/d/1i5lUD7iijY7PdrYWJnaLV7p0mEzNrhzCcGsgTTEmEeI/edit
