### ISSUE TITLE
Community Question: How to add /data/notebooks to Python path

### ISSUE THREAD

**Issue by margaretkennedy** [deephaven/deephaven-docs-community#130]
The DHC web UI writes files to a directory.  Because of this, users can import these files to use in other scripts.  To do this, they need to add /data/notebooks to the python path.  Adding this path by default for all users can be risky because the mechanism used to create and maintain these files is totally insecure -- any browser can edit them. 

Document everything, including the vulnerability. Have instructions on how to add it and explain the reason why.

**Comment by jjbrosnan** [comment]
This question is a partial duplicate of this:

https://deephaven.io/core/docs/reference/community-questions/import-python-script/

We should just add a note to that page about how it's a security vulnerability to do it.
