### ISSUE TITLE
Provide query library functions for computing differences and sort order

### ISSUE THREAD

**Issue by deephaven-internal** [deephaven/deephaven-docs-community#173]
_This issue was auto-generated_

PR: https://github.com/deephaven/deephaven-core/pull/5151
Author: chipkent

## Original PR Body

Query library functions for:
1) Computing array differences
2) Returning sort order

Resolves #5101 
Resolves #3413

**Comment by jjbrosnan** [comment]
This probably only requires updating our auto-imported methods guide. With 0.34 now out, I should add that to my todo list for the week
