### ISSUE TITLE
Port DH-11168: Indexing enhancements to Community.

### ISSUE THREAD

**Issue by deephaven-internal** [deephaven/deephaven-docs-community#174]
_This issue was auto-generated_

PR: https://github.com/deephaven/deephaven-core/pull/3851
Author: lbooker42

## Original PR Body

Port [DH-11168](https://deephaven.atlassian.net/browse/DH-11168): Indexing enhancements to Community.

**Comment by margaretkennedy** [comment]
Same as #77
