### ISSUE TITLE
Use predetermined type converters for UDF arguments

### ISSUE THREAD

**Issue by deephaven-internal** [deephaven/deephaven-docs-community#186]
_This issue was auto-generated_

PR: https://github.com/deephaven/deephaven-core/pull/5291
Author: jmao-denver

## Original PR Body

This builds on top of #5221 to eliminate the need for runtime type check and branching on argument conversion between Java/Python.

Fixes #5112 

Performed that same test as in  https://github.com/deephaven/deephaven-core/issues/5112#issuecomment-1960923785, The numbers are pretty much the same as Exp. #4. 

<img width="1414" alt="image" src="https://github.com/deephaven/deephaven-core/assets/4297243/7b52de0e-12f2-4a08-9d6a-28877f403af4">

**Comment by margaretkennedy** [comment]
Update to user-defined functions
