### ISSUE TITLE
Added support to read partitioned parquet files from S3

### ISSUE THREAD

**Issue by deephaven-internal** [deephaven/deephaven-docs-community#189]
_This issue was auto-generated_

PR: https://github.com/deephaven/deephaven-core/pull/5206
Author: malhotrashivam

## Original PR Body

Closes #5065 

**Breaking Change**: Renamed `KeyValuePartitionLayout` to `FileKeyValuePartitionLayout`.
Reason: `KeyValuePartitionLayout` is now more generic and has common functionalities which are used by both `FileKeyValuePartitionLayout` and a new `URIStreamKeyValuePartitionLayout`. As the name suggestes, `FileKeyValuePartitionLayout` is used to process  key-value partitioned data accessed through java `File` objects, whereas `URIStreamKeyValuePartitionLayout` is used to process `URI`s.

**Comment by margaretkennedy** [comment]
Make sure this is reflected in upcoming Parquet changes.
