### ISSUE TITLE
Refactoring the ParquetTools read/write APIs

### ISSUE THREAD

**Issue by deephaven-internal** [deephaven/deephaven-docs-community#202]
_This issue was auto-generated_

PR: https://github.com/deephaven/deephaven-core/pull/5358
Author: malhotrashivam

## Original PR Body

Marked a number of parquet read/write APIs as `@deprecated`. These include methods that accept java `File` objects, and will be replaced by methods accepting `String` instead. 

Also, added a few new `ParquetInstruction` to replace some APIs: 
- Methods which accept a `TableDefinition`  have been deprecated and will be replaced by setting a new instruction for the definition. 
- Similarly, a new instruction for Parquet file layout has been added, which will replace APIs inside `ParquetTools` which had layout names in the method name (Ex. `readSingleFileTable` will be replaced by `readTable` with layout set as single file).
- Added a new instruction for providing index columns for writing. This will be the new default approach and older APIs have been deleted since those were not released yet.

Also, moved some public utility methods outside of ParquetTools, to prevent internal methods being exposed as APIs.

Initial work for this change was started as part of #5206, and has now been moved over to this PR.

**Comment by margaretkennedy** [comment]
This needs to be rolled into the already ongoing Parquet updates (#21 #45 #22 #48 )
