### ISSUE TITLE
Fix inconsistencies in aggregations and query library functions.

### ISSUE THREAD

**Issue by deephaven-internal** [deephaven/deephaven-docs-community#206]
_This issue was auto-generated_

PR: https://github.com/deephaven/deephaven-core/pull/5368
Author: chipkent

## Original PR Body

Aggregation operations in query library functions and built-in query aggregations are inconsistent.  This PR makes them consistent.  Query library functions were changed.

* `percentile` now returns the primitive type.
* `sum` returns a widened type of `double` for floating point inputs or `long` for integer inputs.
* `product` returns a widened type of `double` for floating point inputs or `long` for integer inputs.
* `cumsum` returns a widened type of `double[]` for floating point inputs or `long[]` for integer inputs.
* `cumprod` returns a widened type of `double[]` for floating point inputs or `long[]` for integer inputs.
* `wsum` returns a widened type of `long` for all integer inputs and `double` for inputs containing floating points.

Note:  Because the types have changed, the NULL return values have changed as well.
 
Resolves #4023

**Comment by margaretkennedy** [comment]
https://github.com/deephaven/deephaven-docs-community/issues/207
