### ISSUE TITLE
Make Numeric.sum return null when there are no inputs or all null inputs

### ISSUE THREAD

**Issue by deephaven-internal** [deephaven/deephaven-docs-community#207]
_This issue was auto-generated_

PR: https://github.com/deephaven/deephaven-core/pull/5461
Author: chipkent

## Original PR Body

Make Numeric.sum return null when there are no inputs or all null inputs.  This makes the method consistent with the aggregations.

**Comment by jjbrosnan** [comment]
This ticket should require zero docs work. We don't document this anywhere, and it's just a fix, not an actual change to the API.
