### ISSUE TITLE
fix!: statistical functions should return `null` when provided a vector of only `null` values

### ISSUE THREAD

**Issue by deephaven-internal** [deephaven/deephaven-docs-community#239]
_This issue was auto-generated_

PR: https://github.com/deephaven/deephaven-core/pull/5606
Author: lbooker42

## Original PR Body

Updated Numeric functions and tests:

- avg
- absAvg
- var
- wvar
- std
- wstd
- ste
- wste
- tstat
- wtstat
- median - had incorrect behavior when `null` values present
- percentile - had incorrect behavior when `null` values present
- cov
- cor

Updated UpdateBy aggregations and tests:

- RollingAvg
- RollingStd

Updated AggBy aggregations:

- avg
- var
- std
- ReVar
- ReAvg

Will close #5564

**Comment by jjbrosnan** [comment]
I don't think this ticket warrants any actual docs work. It fixes null handling behavior of several statistical functions, and is related to tickets that widened return types.

The new null handling behavior is what users should expect to happen, and should not require any discussion in documentation.

**Comment by alexpeters1208** [comment]
I looked around in the docs and I agree - no work needed.
