### ISSUE TITLE
feat: Add auto-legalization for Iceberg Schema column names.

### ISSUE THREAD

**Issue by deephaven-internal** [deephaven/deephaven-docs-community#259]
_This issue was auto-generated_

PR: https://github.com/deephaven/deephaven-core/pull/5746
Author: lbooker42

## Original PR Body

Will close #5714 when merged.

**Comment by margaretkennedy** [comment]
Relates to [Iceberg PR](https://github.com/deephaven/deephaven.io/pull/4101)
