### ISSUE TITLE
Data in > Live > Deephaven's time table

### ISSUE THREAD

**Issue by margaretkennedy** [deephaven/deephaven-docs-community#28]
See "Working with DH tables / Creating tables"

@pchambre to review

**Comment by margaretkennedy** [comment]
Will assign to Devon - he is not currently in the repo.

**Comment by devonpallison** [comment]
Draft here:
https://docs.google.com/document/d/1-RrsnGJnTBOGCkGebyDSiMgyW3Gn51E6Xz6_wBXcO38/edit
PR here:
https://github.com/deephaven/deephaven.io/pull/3832
