### ISSUE TITLE
Controlling table update frequency 

### ISSUE THREAD

**Issue by margaretkennedy** [deephaven/deephaven-docs-community#285]
This topic needs to be fully covered in Community. 

https://deephaven.io/enterprise/docs/development/ltm/

**Comment by margaretkennedy** [comment]
This is : https://deephaven.io/core/docs/conceptual/query-engine/engine-locking/

We need to update Enterprise docs.

**Comment by jjbrosnan** [comment]
What actual work does this ticket entail? @margaretkennedy
