### ISSUE TITLE
feat!:  Add infer_objects argument to the to_table() function in the DH pandas module

### ISSUE THREAD

**Issue by deephaven-internal** [deephaven/deephaven-docs-community#308]
_This issue was auto-generated_

PR: https://github.com/deephaven/deephaven-core/pull/6024
Author: jmao-denver

## Original PR Body

Fixes #6019 

BREAKING CHANGE: the default behavior is changed to converting the object-type columns in the given data frame first before creating a DH table from it. While this change would result in much more sensible column types in DH, e.g. String vs. PyObject for object type column with only strings, it however will break user code written to handle the PyObject type columns in the result table.

**Comment by jjbrosnan** [comment]
This issue is closed by https://github.com/deephaven/deephaven.io/pull/4382.
