### ISSUE TITLE
feat!: Support Multijoin in the Python client

### ISSUE THREAD

**Issue by deephaven-internal** [deephaven/deephaven-docs-community#318]
_This issue was auto-generated_

PR: https://github.com/deephaven/deephaven-core/pull/6020
Author: jmao-denver

## Original PR Body

Fixes #5884

BREAKING CHANGE: the `table()` method on `MultiJoinTable` has been changed to `@property`, which means to access the underlying table of a multi join result, the user can no longer call the `table()` method but instead just use the `table` attribute on a `MultiJoinTable` instance.

**Comment by jjbrosnan** [comment]
closed by https://github.com/deephaven/deephaven.io/pull/4403
