### ISSUE TITLE
Data in > Live > JSON 

### ISSUE THREAD

**Issue by margaretkennedy** [deephaven/deephaven-docs-community#34]
Sub-category is JSON (e.g., from REST). 

https://github.com/deephaven/deephaven-core/pull/2975

**Comment by jjbrosnan** [comment]
What's the scope of this guide? The only two ways I know how to get JSON data into Deephaven:

- Kafka
- Websockets/requests/etc.

However, Kafka JSON has its own ticket.

I'm not sure we have enough content to write about here until more of Devin's new JSON stuff gets merged.

**Comment by margaretkennedy** [comment]
> What's the scope of this guide? The only two ways I know how to get JSON data into Deephaven:
> 
> * Kafka
> * Websockets/requests/etc.
> 
> However, Kafka JSON has its own ticket.
> 
> I'm not sure we have enough content to write about here until more of Devin's new JSON stuff gets merged.

It's quite probable this was more of a "wish list" item. I'll move it to the backlog.
