### ISSUE TITLE
Getting Started > Other installation patterns > Install and run without Docker

### ISSUE THREAD

**Issue by margaretkennedy** [deephaven/deephaven-docs-community#36]
Edit: https://deephaven.io/core/docs/how-to-guides/install-and-run-natively/
reviewer = @niloc132 

PR https://github.com/deephaven/deephaven.io/pull/3871

**Comment by stanbrub** [comment]
Following the instructions for 0.33.3 brings up a DH screen asking for a token.  I've always turned this off, but what should we tell the user?

**Comment by stanbrub** [comment]
@niloc  The `server-jetty-0.33.3/bin` directory has a `start.bat'.  Does that mean we are supporting Windows?  Should that be in this doc as well?

**Comment by stanbrub** [comment]
@margaretkennedy There appear to be three ways to install Deephaven without Docker
- Download Deephaven Tar and Python Wheel (Python Session)
- Download Deephaven wheel (Python Session)
- Download Deephaven Tar and run with Config (Groovy Session)

There is no Groovy counterpart to this doc like there is with launch-build.  Two docs would be identical except for a few lines.  I think I can make this work in the existing file, but it seems inconsistent.  We could do that with the plan of reconciling things later, or make another file like we have with launch-build.  Thoughts?
