### ISSUE TITLE
Getting Started > Other installation patterns > Build from source

### ISSUE THREAD

**Issue by margaretkennedy** [deephaven/deephaven-docs-community#37]
Edit: https://deephaven.io/core/docs/how-to-guides/launch-build/

PR https://github.com/deephaven/deephaven.io/pull/3862

reviewer = @niloc132

**Comment by stanbrub** [comment]
This part is wrong because _printVersion_ produces a version with a different format than the python wheel.
```
pip install "py/server/build/wheel/deephaven_core-<version>-py3-none-any.whl[autocomplete]"
Where <version> is replaced with the Gradle version in use:
./gradlew -q printVersion
```
So we could:
- Explain how to translate the version to the right format
- Provide a find command to get the correct wheel file (there should be only one, right?)

**Comment by devinrsmith** [comment]
I've been preferring to use `--find-links`, as it doesn't require us to know the physical wheel name:

```shell
pip install --find-links py/server/build/wheel "deephaven-core[autocomplete]==<version>"
```

For example, during development of 0.34.0:

```shell
pip install --find-links py/server/build/wheel "deephaven-core[autocomplete]==0.34.0+snapshot"
```

**Comment by devinrsmith** [comment]
I bet this could even be done without any version:

```shell
pip install --find-links py/server/build/wheel "deephaven-core[autocomplete]"
```

**Comment by stanbrub** [comment]
This appears to work.  Thanks.  
> ```shell
> pip install --find-links py/server/build/wheel "deephaven-core[autocomplete]"
> ```

**Comment by stanbrub** [comment]
Is there any reason we need to keep this the Note `If you prefer not to use autocomplete, remove `[autocomplete]` from the wheel installation.` ???
