### ISSUE TITLE
Getting Started > Java / Groovy Quickstart

### ISSUE THREAD

**Issue by margaretkennedy** [deephaven/deephaven-docs-community#5]
PR: https://github.com/deephaven/deephaven.io/pull/3921

**Comment by stanbrub** [comment]
@margaretkennedy In making a Groovy version of this Quickstart guide, there are links to other markdown files that the Python version has, but the Groovy version does not.  Is making these markdown files for Groovy part of this exercise, or is that being handled elsewhere?   (Example below.)
```
../how-to-guides/data-import-export/csv-import.md), [Parquet files](../how-to-guides/data-import-export/parquet-single.md
```
It looks like many of the needed groovy markdown files are there, just not in the same directory structure as the Python markdown.

**Comment by margaretkennedy** [comment]
> @margaretkennedy In making a Groovy version of this Quickstart guide, there are links to other markdown files that the Python version has, but the Groovy version does not. Is making these markdown files for Groovy part of this exercise, or is that being handled elsewhere? (Example below.)
> 
> ```
> ../how-to-guides/data-import-export/csv-import.md), [Parquet files](../how-to-guides/data-import-export/parquet-single.md
> ```
> 
> It looks like many of the needed groovy markdown files are there, just not in the same directory structure as the Python markdown.

No, we will add any missing content separately! CSV should be there, but we're working on Parquet and Kafka down the line.

**Comment by stanbrub** [comment]
@margaretkennedy I really am going down a rat hole here with links in this document.  Much of this is caused by the last section that points users to the How-To Guide.  Is it really necessary to list all these links like this?  Is there no way to reference the root of said How-To Guide.  I'm up to 21 added/changed Groovy files and directories with more on the way. Many of those will need to be converted from python, because there was no Groovy counterpart.
```
- [Import CSV files](../how-to-guides/data-import-export/csv-import.md)
- [Write and read Parquet files](../how-to-guides/data-import-export/parquet-single.md)
- [Connect to a Kafka stream](../how-to-guides/data-import-export/kafka-stream.md)
- [Execute SQL Queries](../how-to-guides/data-import-export/execute-sql-queries.md)
- [Create and organize notebooks using the File Explorer](/core/docs/how-to-guides/user-interface/file-explorer/)
- [Create plots without writing queries using the Chart Builder](/core/docs/how-to-guides/user-interface/chart-builder/)
- [Filter your data without writing queries](/core/docs/how-to-guides/user-interface/filters/)
...
```

**Comment by stanbrub** [comment]
> > @margaretkennedy In making a Groovy version of this Quickstart guide, there are links to other markdown files that the Python version has, but the Groovy version does not. Is making these markdown files for Groovy part of this exercise, or is that being handled elsewhere? (Example below.)
> > ```
> > ../how-to-guides/data-import-export/csv-import.md), [Parquet files](../how-to-guides/data-import-export/parquet-single.md
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It looks like many of the needed groovy markdown files are there, just not in the same directory structure as the Python markdown.
> 
> No, we will add any missing content separately! CSV should be there, but we're working on Parquet and Kafka down the line.

So do I just leave broken links with a comment around them?
