### ISSUE TITLE
Working with Deephaven tables > Deephaven queries > User-defined functions

### ISSUE THREAD

**Issue by margaretkennedy** [deephaven/deephaven-docs-community#55]

**Comment by elijahpetty** [comment]
Outline: https://docs.google.com/document/d/1xJiSVST4kB4KlHpJOtQ7nXCmoTWVXJGO8lP6ZNKCsOQ/edit

**Comment by jjbrosnan** [comment]
It sounds like this article should replace this and maybe others:

https://deephaven.io/core/docs/how-to-guides/simple-python-function/

I'm going to move forward based on Elijah's outline and this notion.
